### ISSUE TITLE
Implement Main Screen and NavBar with PrimeNg 

### ISSUE THREAD

**Issue by Kjamil44** [Kjamil44/AccessControl#2]

**Comment by WebZaLeb** [comment]
Menu Bar is implemented with primeNg
**TODO**:  
               - SiteSelected SideBar
               - Dashboard Main Screen implementation with graphs and stats

**Comment by Kjamil44** [comment]
Menu Bar is implemented with primeNg
TODO:
- SiteSelected SideBar
- Dashboard Main Screen implementation with graphs and stats

**Comment by Kjamil44** [comment]
Dashboards will be created after every component is converted to prime ng

**Comment by Kjamil44** [comment]
TODO: 
Side bar for Select a Site feature will be swapped with primeNg dropdown instead.

**Comment by Kjamil44** [comment]
Temporary site select, list all locks with site name column will be present

**Comment by Kjamil44** [comment]
Prime Ng Components for Dashboard: https://primeng.org/chart
Remove Kendo Notification Toast and use primeNg one: https://primeng.org/toast

**Comment by Kjamil44** [comment]
TODO: 

1. Update Sites Pie chart so the data will be all sites by locks created on them
2. Update Locks Pie Chart so the data will be all locks by how many allowed users to enter they have
3. Create list of how many cardhorders have been created in the last six months from Now
4. Update Welcome Text
